# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'trakt-involves' do
    use_frameworks!

    pod 'R.swift'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Alamofire'
    pod 'AlamofireObjectMapper'
    pod 'AlamofireActivityLogger'
    pod 'ObjectMapper'
    pod 'PKHUD'
    pod 'Kingfisher'
    

  target 'trakt-involvesTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

end
